# Generated by Django 3.2.5 on 2021-07-19 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0012_auto_20180315_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritenode',
            name='node_s',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Topic'),
        ),
        migrations.AddField(
            model_name='topicvote',
            name='topic_s',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritenode',
            unique_together={('user', 'node_s')},
        ),
        migrations.AlterUniqueTogether(
            name='topicvote',
            unique_together={('user', 'topic_s')},
        ),
        migrations.RemoveField(
            model_name='favoritenode',
            name='node',
        ),
        migrations.RemoveField(
            model_name='topicvote',
            name='topic',
        ),
    ]
