# Generated by Django 3.2.5 on 2021-07-20 01:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0013_auto_20210719_2341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='signedinfo',
            unique_together={('user', 'date')},
        ),
    ]
