# Generated by Django 3.2.5 on 2021-07-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0040_auto_20180315_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='nodelink',
            name='author',
        ),
        migrations.RemoveField(
            model_name='nodelink',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='author',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.AddField(
            model_name='comments',
            name='author_s',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Topic 作者'),
        ),
        migrations.AddField(
            model_name='comments',
            name='topic_s',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Topic ID'),
        ),
        migrations.AddField(
            model_name='nodelink',
            name='author_s',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Link作者'),
        ),
        migrations.AddField(
            model_name='nodelink',
            name='category_s',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Node分类'),
        ),
        migrations.AddField(
            model_name='topic',
            name='author_s',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Topic作者'),
        ),
        migrations.AddField(
            model_name='topic',
            name='category_s',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Go分类'),
        ),
    ]
